### ISSUE TITLE
Dúvida: como será feito o select

### ISSUE THREAD

**Issue by marciofrayze** [Nucleo-235/roupa-livre-api#1]
Como será feito o select no banco para obter os dados das roupas a partir da geolocalização? Não entendi o motivo de colocar os índices latitude e longitude no usuário:

`add_index :users, [:lat, :lng]`

Como está usando postgreSQL, acho que a melhor forma de fazer a busca seria usando a extensão postgis (http://postgis.net), não?

**Comment by hrangel** [comment]
Oi @mfdavid realmente usar a postgis teria sido uma boa também, não sei entretanto como seria a integração dela com o rails.

Atualmente adicionados ambas propriedades no User, pois no Roupa Livre a busca sempre é em cima de onde o User está naquela hora, e depois buscamos usando a gem [geokit-rails](https://github.com/geokit/geokit-rails).

Usamos ela para ordenar os resultados:
`@apparels = @apparels.joins(:user).by_distance(:origin => current_user)`

**Comment by hrangel** [comment]
@mfdavid se você tiver uma sugestão sobre como alterar para usar a solução que você enviou estamos mais que abertos!!

**Comment by marciofrayze** [comment]
Não conhecia essa gem, parece interessante. Fiz a pergunta pq nos aplicativos que fiz usando geolocalização essa foi a parte que me deu mais trabalho. Mas no meu caso usei o MongoDB, que nativamente já tem algumas formas de fazer selects otimizados para geolocalização, mas fiquei interessado em como resolver isso no postgresql, e até agora a única solução que tinha encontrado era usando a extensão postgis.
Essa gem que mostrou parece bem interessante e bem prática, só não entendi se ela faz alguma otimização no select ou se faz um select full na tabela toda (o que pode ser meio ruim em termos de performance numa base muito grande). Quando tiver um tempo vou dar uma olhada direito nela, obrigado =)
